package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class CustomercylindersBean 
{
protected int id   = 0;
protected Date createdTime ;
protected Date updatedTime ;
protected String customerId ;
protected String cylinderId ;
protected String quantity ;
protected String price ;
protected String discount ;
protected String totalPrice ;
protected String vat ;
protected String cylinderreturn ;
protected String cylinderReturnTruck;
protected String cylinderDeliverTruck,accessoriesId;

public String getAccessoriesId() {
	return accessoriesId;
}
public void setAccessoriesId(String accessoriesId) {
	this.accessoriesId = accessoriesId;
}
public int getId() {
	return id;
}
public void setId(int id) {
	this.id = id;
}
public Date getCreatedTime() {
	return createdTime;
}
public void setCreatedTime(Date createdTime) {
	this.createdTime = createdTime;
}
public Date getUpdatedTime() {
	return updatedTime;
}
public void setUpdatedTime(Date updatedTime) {
	this.updatedTime = updatedTime;
}
public String getCustomerId() {
	return customerId;
}
public void setCustomerId(String customerId) {
	this.customerId = customerId;
}
public String getCylinderId() {
	return cylinderId;
}
public void setCylinderId(String cylinderId) {
	this.cylinderId = cylinderId;
}
public String getQuantity() {
	return quantity;
}
public void setQuantity(String quantity) {
	this.quantity = quantity;
}
public String getPrice() {
	return price;
}
public void setPrice(String price) {
	this.price = price;
}
public String getDiscount() {
	return discount;
}
public void setDiscount(String discount) {
	this.discount = discount;
}
public String getTotalPrice() {
	return totalPrice;
}
public void setTotalPrice(String totalPrice) {
	this.totalPrice = totalPrice;
}
public String getVat() {
	return vat;
}
public void setVat(String vat) {
	this.vat = vat;
}
public String getCylinderreturn() {
	return cylinderreturn;
}
public void setCylinderreturn(String cylinderreturn) {
	this.cylinderreturn = cylinderreturn;
}
public String getCylinderReturnTruck() {
	return cylinderReturnTruck;
}
public void setCylinderReturnTruck(String cylinderReturnTruck) {
	this.cylinderReturnTruck = cylinderReturnTruck;
}
public String getCylinderDeliverTruck() {
	return cylinderDeliverTruck;
}
public void setCylinderDeliverTruck(String cylinderDeliverTruck) {
	this.cylinderDeliverTruck = cylinderDeliverTruck;
}



}