package com.aurospaces.neighbourhood.bean;


import java.util.Date;


/**
 *
 * @author autogenerated
 */



public class KhaibarUsersBean 
{
protected int id   = 0;
protected Date createdTime ;
protected Date updatedTime ;
protected String userName ;
protected String password ;
protected String roleId ;
protected String status ;
protected String edit;
protected String delete1,userstatus ;



public String getUserstatus() {
	return userstatus;
}
public void setUserstatus(String userstatus) {
	this.userstatus = userstatus;
}
public String getUserName() {
	return userName;
}
public void setUserName(String userName) {
	this.userName = userName;
}
public String getDelete1() {
	return delete1;
}
public void setDelete1(String delete1) {
	this.delete1 = delete1;
}

protected String mobileapp ;




public String getEdit() {
	return edit;
}
public void setEdit(String edit) {
	this.edit = edit;
}
public String getMobileapp() {
	return mobileapp;
}
public void setMobileapp(String mobileapp) {
	this.mobileapp = mobileapp;
}
public int getId()
{
  return id;
}
public void setId(final int id)
{
  this.id = id;
}
public Date getCreatedTime()
{
  return createdTime;
}
public void setCreatedTime(final Date createdTime)
{
  this.createdTime = createdTime;
}
public Date getUpdatedTime()
{
  return updatedTime;
}
public void setUpdatedTime(final Date updatedTime)
{
  this.updatedTime = updatedTime;
}

public String getPassword()
{
  return password;
}
public void setPassword(final String password)
{
  this.password = password;
}
public String getRoleId()
{
  return roleId;
}
public void setRoleId(final String roleId)
{
  this.roleId = roleId;
}
public String getStatus()
{
  return status;
}
public void setStatus(final String status)
{
  this.status = status;
}


}